OAS-5749 | Add notebook support
arangodb-managed/oasisctl pull request #134
Opened 2022-09-28 09:05 UTC by forgems

2022-09-28 09:47 UTC, lakhansamani requested changes
Minor comments,
Further looks good to me

2022-09-28 09:47 UTC, lakhansamani commented on Makefile
> +			github.com/arangodb-managed/apis@OAS-5677 \
Don't forget

2022-09-28 09:52 UTC, Robert-Stam reviewed
See remarks

2022-09-28 09:52 UTC, Robert-Stam commented on Makefile
> +			github.com/arangodb-managed/apis@OAS-5677 \
don't forget

2022-09-28 09:52 UTC, Robert-Stam commented on cmd/notebook/create_notebook.go
> +			f.StringVarP(&cargs.OrganizationID, "organization-id", "o", cmd.DefaultOrganization(), "Identifier of the organization to create the deployment in")
deployment --> notebook

2022-09-28 09:52 UTC, Robert-Stam commented on cmd/notebook/create_notebook.go
> +			f.StringVarP(&cargs.ProjectID, "project-id", "p", cmd.DefaultProject(), "Identifier of the project to create the deployment in")
deployment --> notebook

2022-09-28 09:52 UTC, Robert-Stam commented on cmd/notebook/create_notebook.go
> +			f.Int32VarP(&cargs.DiskSize, "disk-size", "s", 0, "Disk size that has to be attached to given notebook")
Disk size (in Gib)

2022-09-28 09:52 UTC, Robert-Stam commented on cmd/notebook/delete_notebook.go
> +				fmt.Println(format.Notebook(notebook, cmd.RootArgs.Format))
why this in delete?

2022-09-28 09:52 UTC, Robert-Stam commented on cmd/notebook/create_notebook.go
> +				fmt.Printf("%#v\n", created)
fmt.Println(format.Notebook(crreated, cmd.RootArgs.Format))

2022-09-28 09:52 UTC, Robert-Stam commented on cmd/notebook/list_notebooks.go
> +				DeploymetnID   string
DeploymetnID --> DeploymentID

2022-09-28 09:52 UTC, Robert-Stam commented on cmd/notebook/list_notebooks.go
> +				for {
there was a forEach available, however this works as well.

2022-09-28 09:52 UTC, Robert-Stam commented on pkg/format/notebook.go
> +			{"created-at", formatTime(opts, x.GetCreatedAt())},
phase?

2022-10-05 11:30 UTC, lakhansamani approved these changes
LGTM

2022-10-05 11:41 UTC, Robert-Stam approved these changes
LGTM

2022-10-05 11:47 UTC, merged