OAS-1488 | Create backup policy commands
arangodb-managed/oasisctl pull request #87
Opened 2020-09-17 14:10 UTC by Skarlso

2020-09-17 15:21 UTC, ewoutp commented on cmd/data/create_backup.go
> -		&cobra.Command{
Please revert this change.
Then have a global variable like this

var createBackupCmd = cmd.InitCommand(cmd.CreateCmd, &cobra.Command{...}...)

2020-09-17 15:21 UTC, ewoutp commented on cmd/data/create_backup_policy.go
> +			f.StringVar(&cargs.emailNotification, "email-notificatetion", "", "Email notification setting (Never|FailureOnly|Always)")
notificatetion -> notification

2020-09-17 15:21 UTC, ewoutp commented on cmd/data/create_backup_policy.go
> +			f.BoolVar(&cargs.locked, "locked", false, "If set, this backup policy cannot be deleted. To delete, first update the with locked set to false.")
Please remove this. None of the other resource have it like this

2020-09-17 15:21 UTC, ewoutp commented on cmd/data/delete_backup.go
> -		&cobra.Command{
Same as above

2020-09-17 15:21 UTC, ewoutp commented on cmd/data/get_backup.go
> -		&cobra.Command{
Same as above

2020-09-17 15:21 UTC, ewoutp commented on cmd/data/list_backup_policies.go
> +		listBackupsCmd,
This is not right. It should be a `list backup` command so you can do `list backup policies` instead of `list backups policies`

2020-09-17 15:21 UTC, ewoutp commented on cmd/data/update_backup.go
> -		&cobra.Command{
Same as above

2020-09-17 15:21 UTC, ewoutp commented on cmd/data/update_backup_policy.go
> +			f.BoolVar(&cargs.locked, "locked", false, "If set, this backup policy cannot be deleted. To delete, first update the with locked set to false.")
Please remove this

2020-09-17 15:21 UTC, ewoutp commented on pkg/format/backup_policy.go
> +		{"locked", x.GetLocked()},
use formatBool(...)

2020-09-17 15:21 UTC, ewoutp commented on pkg/format/backup_policy.go
> +func parseBackupPolicyToKeyValueList(x *backup.BackupPolicy, opts Options) []kv {
Don't understand the "parse" part of the name

2020-09-18 09:31 UTC, Robert-Stam requested changes
See remarks

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/create_backup_policy.go
> +			f.StringVar(&cargs.description, "description", "", "Description of the backup")
backup --> backup policy

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/create_backup_policy.go
> +			f.Int32Var(&cargs.timeofday.minutes, "minutes", 0, "Minutes part of the time of day (0-23)")
(0-23) --> (0-59)

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/create_backup_policy.go
> +					}
add default, which results in error

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/create_backup_policy.go
> +					log.Fatal().Err(err).Msg("Failed to create backup")
backup --> backup policy

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/delete_backup_policy.go
> +
please introduce item := selection.MustSelectBackupPolicy(, so we can use the name to get it as well.
See item := selection.MustSelectDeployment(

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/get_backup_policy.go
> +
please introduce item := selection.MustSelectBackupPolicy(, so we can use the name to get it as well.

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/lock_backup_policy.go
> +				item := selection.MustSelectBackupPolicy(ctx, log, id, backupc)
like here 👍

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/unlock_backup_policy.go
> +					log.Fatal().Err(err).Msg("Failed to unlock backup")
backup --> backup policy

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/update_backup_policy.go
> +				}
for bools you have to check the current vs new, not if the default has been changed?
Or indicate clearly that you have to specify the default value as well to get it updated.

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/update_backup_policy.go
> +			f.Int32Var(&cargs.timeofday.minutes, "minutes", 0, "Minutes part of the time of day (0-23)")
(0-23) --> (0-59)

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/update_backup_policy.go
> +			f.StringVar(&cargs.emailNotification, "email-notificatetion", "", "Email notification setting (Never|FailureOnly|Always)")
email-notificatetion --> email-notification

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/update_backup_policy.go
> +					item.Schedule.ScheduleType = cargs.scheduleType
this line can be removed

2020-09-18 09:31 UTC, Robert-Stam commented on cmd/data/update_backup_policy.go
> +						}
please add default case

2020-09-18 12:31 UTC, Skarlso commented on cmd/data/delete_backup_policy.go
> +
I see that we do that for other delete operations and I will add it, but I would like to voice my concern that for a DELETE to AUTOMATICALLY select something which I wouldn't expect to happen and then delete something because I forgot to set an id, is very risky.

2020-09-18 12:47 UTC, Skarlso commented on cmd/data/update_backup_policy.go
> +				}
I'm used to boolean flags needing explicit `--flag=false` to update from other CLI tools. But you are right that it should be clearly indicated. I'll put it into the description.

2020-09-18 15:15 UTC, Robert-Stam approved these changes
fix typo, then LGTM (did we create tests for them as well?)

2020-09-18 15:15 UTC, Robert-Stam commented on cmd/data/update_backup_policy.go
> +			f.BoolVar(&cargs.upload, "upload", false, "The backup should be uploaded. Set to false explicitely to clear the flag.")
explicitely --> explicitly (more places)

2020-09-18 15:16 UTC, Skarlso commented on cmd/data/update_backup_policy.go
> +			f.BoolVar(&cargs.upload, "upload", false, "The backup should be uploaded. Set to false explicitely to clear the flag.")
Dang it, I really cannot type.

2020-09-18 15:53 UTC, merged